[global]
    dns forwarder = YOUR_INTERNAL_DNS_IP 8.8.8.8
    netbios name = DC01
    realm = YOUR_REALM.LAN
    server role = active directory domain controller
    workgroup = YOUR_WORKGROUP
    idmap_ldb:use rfc2307 = yes
    log file = /var/log/samba/log.samba
    max log size = 10000
    interfaces = 127.0.0.1 YOUR_SERVER_INTERNAL_IP
    bind interfaces only = no
    
    # --- CONFIGURACIÓN PARA WAZUH (Log limpio) ---
    log level = 1 vfs:2
    debug prefix timestamp = no
    debug hires timestamp = no
    debug pid = no
    debug uid = no
    debug class = no
    winbind enum users = no
    winbind enum groups = no

[sysvol]
    path = /var/lib/samba/sysvol
    read only = No

[netlogon]
    path = /var/lib/samba/sysvol/your_realm.lan/scripts
    read only = No

[Expedientes]
    path = /srv/samba/expedientes
    read only = No
    valid users = @YOUR_AUTHORIZED_GROUP_1
    comment = Documentos legales del bufete
    vfs objects = full_audit
    full_audit:syslog = no
    full_audit:prefix = %u|%I|%S
    full_audit:success = mkdirat renameat unlinkat pwrite
    full_audit:failure = connect
    full_audit:log_level = vfs:1

[Gestion]
    path = /srv/samba/gestion
    read only = No
    valid users = @YOUR_AUTHORIZED_GROUP_2
    comment = Documentos del bufete
    vfs objects = full_audit
    full_audit:syslog = no
    full_audit:prefix = %u|%I|%S
    full_audit:success = mkdirat renameat unlinkat pwrite
    full_audit:failure = connect
    full_audit:log_level = vfs:1
